parent-stuff-project/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup',  to: 'users#new'

  get '/login',   to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users 
  resources :places do 
    resources :reviews
  end

end

parent-stuff-project/app/models/place.rb
class Place < ApplicationRecord 
  has_many :reviews
  has_many :users, through: :reviews 

  validates :name, presence: true
  validates :address, presence: true, uniqueness: true 

  CATEGORY=['Store', 'Restaurant', 'Other']
end

parent-stuff-project/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :place

  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

parent-stuff-project/app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :places, through: :reviews

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-])*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Defines a proto feed
  def feed 
    Review.where("user_id = ?", id)
  end

end

parent-stuff-project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception   
  include SessionsHelper 

  private 

    # Confirms a logged-in user
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
end

parent-stuff-project/app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index
    @places = Place.all
  end
  
  def new
    @place = Place.new
  end

  def show
    @place = Place.find(params[:id])
    #@reviews = @user.reviews.paginate(page: params[:page])
  end

  def create  
    @place = Place.new(place_params)
    if @place.save
      flash[:success] = "Your new place was created!"
      redirect_to places_path
    else 
      render 'new'
    end
  end
  
  def edit  
    @place = Place.find(params[:id])
  end

  def update
    @place = Place.find(params[:id])
    if @place.update_attributes(place_params)
      flash[:success] = "Place updated"
      redirect_to @place
    else 
      render 'edit'
    end
  end   

  def destroy 
    Place.find(params[:id]).destroy
    flash[:success] = "Place deleted!"
    redirect_to places_url
  end

  private
  
  def place_params
    params.require(:place).permit(:name, :address, :website, :phone_number, :category, :changing_tables, :nursing_room, :high_chairs, :family_bathroom)
  end


end

parent-stuff-project/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  def index
    @reviews = Place.find_by(id:params[:place_id]).reviews
  end

  
  def new 
    @review = Review.new
    @review.place_id = params[:place_id]
  end

  def create
    @review = current_user.reviews.build(review_params)
    #@place_options = Places.all.map{ |p| [p.name, p.id] }
    
    if @review.save
      flash[:success] = "Review created!"
      redirect_to root_url
    else      
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @review.destroy
    flash[:success] = "Review deleted"
    redirect_to request.referrer || root_url
  end

  private

    def review_params
      params.require(:review).permit(:content, :place_id)
    end

    def correct_user
      @review = current_user.reviews.find_by(id: params[:id])
      redirect_to root_url if @review.nil?
    end

end

parent-stuff-project/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user =  User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user 
      redirect_back_or user 
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end 
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

parent-stuff-project/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @review = current_user.reviews.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
  
end

parent-stuff-project/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user 
      flash[:success] = "Welcome to Parent Stuff!"
      redirect_to @user
    else 
      render 'new'
    end
  end

  def edit  
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else 
      render 'edit'
    end
  end      

  def destroy 
    User.find(params[:id]).destroy
    flash[:success] = "User deleted!"
    redirect_to users_url
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  # Before filters
  
  # Confirms the correct user
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  # Confirms an admin user
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

end

parent-stuff-project/app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Parent Stuff"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
  
end

parent-stuff-project/app/helpers/places_helper.rb
module PlacesHelper
end

parent-stuff-project/app/helpers/reviews_helper.rb
module ReviewsHelper
end

parent-stuff-project/app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user 
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the current logged-in user, if any
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil 
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
  
end

parent-stuff-project/app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt:user.name, class: "gravatar")
  end

end

parent-stuff-project/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    By <a href="http://www.marieldotcode.com/">Mariel de la Garza</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

parent-stuff-project/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "parent stuff", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Places", places_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

parent-stuff-project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= render 'layouts/shim' %>  
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

parent-stuff-project/app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>

    <%= f.label :website %>
    <%= f.text_field :website, class: 'form-control' %>

    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>

    <%= f.label :category %>
    <%= f.select :category, Place::CATEGORY %>

    <%= f.label :changing_tables, class: "checkbox inline" do %>
      <%= f.check_box :changing_tables %>
      <span>Changing Tables</span>
    <% end %>

    <%= f.label :family_bathroom, class: "checkbox inline" do %>
      <%= f.check_box :family_bathroom %>
      <span>Family Bathroom</span>
    <% end %>

    <%= f.label :high_chairs, class: "checkbox inline" do %>
      <%= f.check_box :high_chairs %>
      <span>High Chairs</span>
    <% end %>

    <%= f.label :nursing_room, class: "checkbox inline" do %>
      <%= f.check_box :nursing_room %>
      <span>Nursing Room</span>
    <% end %>


  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

parent-stuff-project/app/views/places/edit.html.erb
<% provide(:title, "Edit place") %>
<% provide(:button_text, 'Save changes') %>
<h1>Update Place Details</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

parent-stuff-project/app/views/places/index.html.erb
<% provide(:title, 'All places') %>
<h1>All places</h1>

<h2>Don't see a place you're looking for?</h2>
<h2><%= link_to "Click here to create a new place!", new_place_path%></h2>

<ul class="places">
  <% @places.each do |place| %>
    <li>
      <%= link_to place.name, place %>
    </li>
  <% end %>
</ul>

parent-stuff-project/app/views/places/new.html.erb
<% provide(:title, 'Create Place') %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

parent-stuff-project/app/views/places/show.html.erb
<% provide(:title, @place.name) %>
<h1>
  <%= @place.name %>
</h1>

<ul>
  <li>Address:      <%= @place.address %></li>
  <br>
  <li>Website:      <%= @place.website %></li>
  <br>
  <li>Phone Number: <%= @place.phone_number %></li>
  <br>
  <li>Category:     <%= @place.category %></li>
  <br>
  <li>Changing Tables? 
    <%if @place.changing_tables == true %>
      <span>Yes!</span>
    <%else%>
      <span>No</span>
    <%end%>
  </li>
  <br>
    <li>Family bathroom? 
      <%if @place.family_bathroom == true %>
        <span>Yes!</span>
      <%else%>
        <span>No</span>
      <%end%>
    </li>
  <br>
  <li>High chairs? 
    <%if @place.high_chairs == true %>
      <span>Yes!</span>
    <%else%>
      <span>No</span>
    <%end%>
  </li>
  <br>
  <li>Nursing room? 
    <%if @place.nursing_room == true %>
      <span>Yes!</span>
    <%else%>
      <span>No</span>
    <%end%>
  </li>
</ul>

<h2>Have some of these details changed?</h2>
<h2><%= link_to "Update them and share with other parents!", edit_place_path%></h2>

<h1>Reviews submitted about <%= @place.name %></h1>
<ul>
  <% @place.reviews.each do |review| %>
    <li><%= review.content %>
    <br>
    Submitted by <%= review.user.name%></li>
  <%end%>
</ul>

parent-stuff-project/app/views/reviews/_review.html.erb
<li id="review-<%= review.id %>">
  <%= link_to gravatar_for(review.user, size: 50), review.user %>
  <span class="user"><%= link_to review.user.name, review.user %></span>
  <span class="content"><%= review.content %></span>
  <span class="user">Visit the profile page for <%= link_to review.place.name, review.place %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(review.created_at) %> ago.
    <% if current_user?(review.user) %>
      <%= link_to "delete", review, method: :delete, data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

parent-stuff-project/app/views/reviews/index.html.erb
<%= @reviews.first.place.name %>


parent-stuff-project/app/views/reviews/new.html.erb
<%= render 'shared/review_form' %>

parent-stuff-project/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

parent-stuff-project/app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="reviews">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

parent-stuff-project/app/views/shared/_review_form.html.erb
<%= form_for([@review.place, @review]) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new review...." %>
    <br>
    <span>Choose a place for this review from the dropdown menu.</span>
    <%= f.collection_select :place_id, Place.order(:name),:id,:name, include_blank: true %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

parent-stuff-project/app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %>
<span><%= link_to "View my profile", current_user %></span>
<span><%= pluralize(current_user.reviews.count, "review") %></span>

parent-stuff-project/app/views/static_pages/_logged_in_home.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= render 'shared/user_info' %>
    </section>
    <section class="review_form">
      <%= render 'shared/review_form' %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3>Review Feed</h3>
    <%= render 'shared/feed'%>
  </div>
</div>

parent-stuff-project/app/views/static_pages/_logged_out_home.html.erb
<div class="center jumbotron">
    <h1>Parent Stuff</h1>
  
    <h2>The stuff parents need, where they need it.</h2>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>

  <%= link_to image_tag("flatiron_logo.JPG", alt: "Flatiron School Logo"), 'https://flatironschool.com' %>

parent-stuff-project/app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  This app is to help parents crowd source information about features and amenities commonly-needed when out with their children, including changing-tables, nursing rooms, and family restrooms.
  <br>
  <br>
  This was created as the Rails project for Flatiron's Online Software Engineering program.
</p>

parent-stuff-project/app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Mariel via her website's <a href="https://www.marieldotcode.com/contact">contact page</a>.
</p>

parent-stuff-project/app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  For an excellent reference, see the <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em></a> book.
</p>

parent-stuff-project/app/views/static_pages/home.html.erb
<% if logged_in? %>
   <%= render 'static_pages/logged_in_home' %>
<% else %>
  <%= render  'static_pages/logged_out_home'%>
<% end %>

<!-- call render with the full path (including static_pages) to make sure that rendering the home pages works in all controllers, not just the Static Pages controller -->

parent-stuff-project/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

parent-stuff-project/app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
  <% end %>
</li>

parent-stuff-project/app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">Change</a>
    </div>
  </div>
</div>

parent-stuff-project/app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <%= render @users %>
  <% end %>
</ul>

<%= will_paginate %>

parent-stuff-project/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

parent-stuff-project/app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.reviews.any? %>
      <h3>reviews (<%= @user.reviews.count %>)</h3>
      <ol class="reviews">
        <%= render @reviews %>
      </ol>
      <%= will_paginate @reviews %>
    <% end %>
  </div>
</div>