parent_stuff/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  get '/help', to: 'static_pages#help'

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'
   
  get '/signup', to: 'users#new'

  resources :places do
    resources :features 
  end

  resources :users 
  resources :sessions, only: [:new, :create, :destroy]

end

parent_stuff/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

parent_stuff/app/models/feature.rb
class Feature < ApplicationRecord
  belongs_to :place
end

parent_stuff/app/models/place.rb
class Place < ApplicationRecord
  has_many :features  
  has_many :reviews 
  has_many :users, though :reviews
end

parent_stuff/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user 
  belongs_to :place 
end

parent_stuff/app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :places, through: :reviews  
end

parent_stuff/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

parent_stuff/app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index 
  end 

  def new
  end

  def create
  end

  def edit 
  end

  def update 
  end

  def destroy 
  end

end

parent_stuff/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

parent_stuff/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

parent_stuff/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index 
  end 

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save 
      session[:user_id]=@user.id
      user_path(@user)
    else 
      @user.errors.full_messages
    end
  end

  def show
  end

  def edit 
  end

  def update 
  end

  def destroy 
  end

  private 

  def user_params
    params.require(:user), permit(:username, :email, :password)
  end

end

parent_stuff/app/helpers/application_helper.rb
module ApplicationHelper

  #Returns the full title on a per-page basis
  
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty? 
      base_title
    else
      page_title + " | " + base_title
    end
  end
  
end

parent_stuff/app/helpers/places_helper.rb
module PlacesHelper
end

parent_stuff/app/helpers/sessions_helper.rb
module SessionsHelper
end

parent_stuff/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

parent_stuff/app/helpers/users_helper.rb
module UsersHelper
end

parent_stuff/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    By <a href="http://www.marieldotcode.com/">Mariel de la Garza</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

parent_stuff/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "parent stuff", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

parent_stuff/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

parent_stuff/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

   <%= render 'layouts/shim'%>

  </head>

  <body>
    <%= render 'layouts/header' %>    
    <div class = "container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

parent_stuff/app/views/places/_form.html.erb
<%= form_for :place do |f| %>
<%= f.label :name%>
<%= f.text_field :name %><br>
<%= f.label :address%>
<%= f.text_field :address %><br>
<%= f.label :phone_number%>
<%= f.text_field :phone_number %><br>
<%= f.label :website%>
<%= f.text_field :website %><br>
<%= f.submit%>
<%end%>

parent_stuff/app/views/places/new.html.erb
<%= render 'form', locals: {place:@place}%>

parent_stuff/app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  This app is to help parents crowd source information about features and amenities commonly-needed when out with their children, including changing-tables, nursing rooms, and family restrooms.

  This was created as the Rails project for Flatiron's Online Software Engineering program.
</p>

parent_stuff/app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Mariel via her website's <a href="https://www.marieldotcode.com/contact">contact page</a>.
</p>

parent_stuff/app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  For an excellent reference, see the <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em> book</a>.
</p>

parent_stuff/app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Parent Stuff</h1>
  <h2>The stuff parents need, where they need it.</h2>

<!--<%= link_to 'Log in', new_session_path %> -->
<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary"%>

parent_stuff/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign Up</h1>
<p>This will be a signup page for new users.</p>

<%= form_for @user do |f| %>
<%= f.label :username %>
<%= f.text_field :username%>
<%= f.label :email%>
<%= f.email_field :email%>
<%= f.label :password%>
<%= f.password_field :password%>
<%= f.submit%>
<%end%>